# Generated by Django 4.1.7 on 2023-03-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('nit', models.CharField(max_length=10, verbose_name='Nit')),
                ('seguroSocial', models.CharField(blank=True, max_length=15, null=True, verbose_name='Seguro Social')),
                ('representante', models.CharField(max_length=100, verbose_name='Representante')),
                ('contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto')),
                ('cargo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='WhatsApp/Telegram')),
                ('sitio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sitio Web')),
                ('actividadE', models.CharField(blank=True, max_length=100, null=True, verbose_name='Actividad Económica')),
                ('actividadS', models.CharField(blank=True, max_length=100, null=True, verbose_name='Actividad de Servicios')),
                ('norma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Norma Contable')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'entity',
                'ordering': ['id'],
            },
        ),
    ]
