# Generated by Django 4.1.7 on 2023-06-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('colegiado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colegiado')),
                ('tipo_auditoria', models.CharField(max_length=50, verbose_name='Tipo de Auditoria')),
                ('periodo', models.CharField(max_length=30, verbose_name='Periodo')),
                ('nombramiento', models.CharField(max_length=30, verbose_name='Nombramiento')),
                ('fecha_nombramiento', models.DateField(verbose_name='Fecha de Nombramiento')),
                ('tareas', models.TextField(blank=True, null=True, verbose_name='Asignacion de tareas')),
                ('tipo', models.CharField(choices=[('Auditor', 'Auditor'), ('Supervisor', 'Supervisor'), ('Otros', 'Otros')], max_length=20, verbose_name='Tipo Colaborador')),
            ],
            options={
                'verbose_name': 'AuditorSupervisor',
                'verbose_name_plural': 'AuditoresSupervisores',
                'db_table': 'auditorSupervisor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Contacto')),
                ('movil', models.CharField(max_length=15, verbose_name='Movil Contacto')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Contacto')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo Contacto')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa en que labora')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contact',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Entidad')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('nit', models.CharField(max_length=10, verbose_name='Nit')),
                ('seguroSocial', models.CharField(blank=True, max_length=15, null=True, verbose_name='Seguro Social')),
                ('representante', models.CharField(max_length=100, verbose_name='Representante')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='WhatsApp/Telegram')),
                ('sitio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sitio Web')),
                ('actividadE', models.CharField(blank=True, max_length=100, null=True, verbose_name='Actividad Económica')),
                ('actividadS', models.CharField(blank=True, max_length=100, null=True, verbose_name='Actividad de Servicios')),
                ('norma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Norma Contable')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'entity',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Tarea')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Finalización')),
                ('descripcion_tarea', models.TextField()),
                ('autor_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.auditorsupervisor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuser')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'task',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_notifica', models.CharField(max_length=50, verbose_name='Nombre Notificante')),
                ('nombramiento', models.CharField(max_length=50, verbose_name='Nombramiento de Auditoria No.')),
                ('fecha_notificacion', models.DateField()),
                ('nota', models.TextField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.entidad')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notification',
                'ordering': ['id'],
            },
        ),
    ]
