# Generated by Django 4.1.7 on 2023-03-18 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('colegiado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colegiado')),
                ('tipo_auditoria', models.CharField(max_length=50, verbose_name='Tipo de Auditoria')),
                ('periodo', models.CharField(max_length=30, verbose_name='Periodo')),
                ('nombramiento', models.CharField(max_length=30, verbose_name='Nombramiento')),
                ('fecha_nombramiento', models.DateField(verbose_name='Fecha de Nombramiento')),
                ('tareas', models.TextField(blank=True, null=True, verbose_name='Asignacion de tareas')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo Colaborador')),
            ],
            options={
                'verbose_name': 'AuditorSupervisor',
                'verbose_name_plural': 'AuditoresSupervisores',
                'db_table': 'auditorSupervisor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Contacto')),
                ('movil', models.CharField(max_length=15, verbose_name='Movil Contacto')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Contacto')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo Contacto')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'contact',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='cargo',
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Tarea')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de Finalización')),
                ('descripcion_tarea', models.TextField()),
                ('autor_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.auditorsupervisor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'task',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_notifica', models.CharField(max_length=50, verbose_name='Nombre Notificante')),
                ('nombramiento', models.CharField(max_length=50, verbose_name='Nombramiento de Auditoria No.')),
                ('fecha_notificacion', models.DateField()),
                ('nota', models.TextField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.entidad')),
                ('nombre_notificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre Notificado')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notification',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='auditorsupervisor',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.entidad'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.contacto'),
        ),
    ]
