# Generated by Django 4.1.7 on 2023-06-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='nombre_notificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre Notificado'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.contacto'),
        ),
        migrations.AddField(
            model_name='auditorsupervisor',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.entidad', verbose_name='Asociar Entidad'),
        ),
    ]
