# Generated by Django 4.1.7 on 2023-03-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auditorsupervisor_contacto_remove_entidad_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa en que labora'),
        ),
    ]
