# Generated by Django 4.1.7 on 2023-03-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_contacto_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={},
        ),
        migrations.AlterModelTable(
            name='contacto',
            table=None,
        ),
    ]
