# Generated by Django 4.1.7 on 2023-03-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_contacto_options_alter_contacto_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['id'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelTable(
            name='contacto',
            table='contact',
        ),
    ]
