# Generated by Django 4.1.7 on 2023-03-31 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_alter_contacto_options_alter_contacto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorsupervisor',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.entidad', verbose_name='Asociar Entidad'),
        ),
        migrations.AlterField(
            model_name='auditorsupervisor',
            name='tipo',
            field=models.CharField(choices=[('Auditor', 'Auditor'), ('Supervisor', 'Supervisor'), ('Otros', 'Otros')], max_length=20, verbose_name='Tipo Colaborador'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de Entidad'),
        ),
    ]
