# Generated by Django 4.1.7 on 2023-06-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30, verbose_name='Referencia')),
                ('actividad', models.TextField(verbose_name='Actividad a realizar')),
                ('fecha_ini', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado Actual PT')),
                ('enero', models.IntegerField(default=0, verbose_name='Enero')),
                ('febrero', models.IntegerField(default=0, verbose_name='Febrero')),
                ('marzo', models.IntegerField(default=0, verbose_name='Marzo')),
                ('abril', models.IntegerField(default=0, verbose_name='Abril')),
                ('mayo', models.IntegerField(default=0, verbose_name='Mayo')),
                ('junio', models.IntegerField(default=0, verbose_name='Junio')),
                ('julio', models.IntegerField(default=0, verbose_name='Julio')),
                ('agosto', models.IntegerField(default=0, verbose_name='Agosto')),
                ('septiembre', models.IntegerField(default=0, verbose_name='Septiembre')),
                ('octubre', models.IntegerField(default=0, verbose_name='Octubre')),
                ('noviembre', models.IntegerField(default=0, verbose_name='Noviembre')),
                ('diciembre', models.IntegerField(default=0, verbose_name='Diciembre')),
                ('totalDias', models.IntegerField(default=0, verbose_name='Total de días')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.BinaryField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nombramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombramiento', models.CharField(max_length=10, unique=True, verbose_name='Nombramiento')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('dias_programados', models.IntegerField(default=0, verbose_name='Días Programados')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customuser')),
            ],
            options={
                'verbose_name': 'Nombramiento',
                'verbose_name_plural': 'Nombramientos',
                'db_table': 'nombramiento',
                'ordering': ['id'],
            },
        ),
    ]
