# Generated by Django 4.1.7 on 2023-06-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.auditorsupervisor', verbose_name='Auditor Responsable'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='nombramiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas.nombramiento', verbose_name='Nombramiento'),
        ),
    ]
