# Generated by Django 4.1.7 on 2023-04-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nombramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombramiento', models.CharField(max_length=10, verbose_name='Nombramiento')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('dias_programados', models.IntegerField(default=0, verbose_name='Días Programados')),
            ],
            options={
                'verbose_name': 'Nombramiento',
                'verbose_name_plural': 'Nombramientos',
                'db_table': 'nombramiento',
                'ordering': ['id'],
            },
        ),
    ]
