# Generated by Django 4.1.7 on 2023-04-11 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_auditorsupervisor_entidad_and_more'),
        ('herramientas', '0002_nombramiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30, verbose_name='Referencia')),
                ('actividad', models.TextField(verbose_name='Actividad a realizar')),
                ('fecha_ini', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado Actual PT')),
                ('enero', models.IntegerField(verbose_name='Enero')),
                ('febrero', models.IntegerField(verbose_name='Febrero')),
                ('marzo', models.IntegerField(verbose_name='Marzo')),
                ('abril', models.IntegerField(verbose_name='Abril')),
                ('mayo', models.IntegerField(verbose_name='Mayo')),
                ('junio', models.IntegerField(verbose_name='Junio')),
                ('julio', models.IntegerField(verbose_name='Julio')),
                ('agosto', models.IntegerField(verbose_name='Agosto')),
                ('septiembre', models.IntegerField(verbose_name='Septiembre')),
                ('octubre', models.IntegerField(verbose_name='Octubre')),
                ('noviembre', models.IntegerField(verbose_name='Noviembre')),
                ('diciembre', models.IntegerField(verbose_name='Diciembre')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.auditorsupervisor', verbose_name='Auditor Responsable')),
                ('nombramiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas.nombramiento', verbose_name='Nombramiento')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
                'ordering': ['id'],
            },
        ),
    ]
