# Generated by Django 4.1.7 on 2023-04-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0003_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
