# Generated by Django 4.1.7 on 2023-04-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0004_actividad_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='totalDias',
            field=models.IntegerField(default=0, verbose_name='Total de días'),
        ),
    ]
