# Generated by Django 4.1.7 on 2023-07-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0004_remove_actividad_totaldias_alter_actividad_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={},
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_ini',
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado_actual',
            field=models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('FINAIZADA', 'Finalizada')], default='EN_PROCESO', max_length=20),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='abril',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='actividad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='agosto',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='auditor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='diciembre',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='enero',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='febrero',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='julio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='junio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='marzo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='mayo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombramiento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='noviembre',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='octubre',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='referencia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='septiembre',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterModelTable(
            name='actividad',
            table=None,
        ),
    ]
