# Generated by Django 4.1.7 on 2023-04-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0005_actividad_totaldias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='abril',
            field=models.IntegerField(default=0, verbose_name='Abril'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='agosto',
            field=models.IntegerField(default=0, verbose_name='Agosto'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='diciembre',
            field=models.IntegerField(default=0, verbose_name='Diciembre'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='enero',
            field=models.IntegerField(default=0, verbose_name='Enero'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='febrero',
            field=models.IntegerField(default=0, verbose_name='Febrero'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='julio',
            field=models.IntegerField(default=0, verbose_name='Julio'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='junio',
            field=models.IntegerField(default=0, verbose_name='Junio'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='marzo',
            field=models.IntegerField(default=0, verbose_name='Marzo'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='mayo',
            field=models.IntegerField(default=0, verbose_name='Mayo'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='noviembre',
            field=models.IntegerField(default=0, verbose_name='Noviembre'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='octubre',
            field=models.IntegerField(default=0, verbose_name='Octubre'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='septiembre',
            field=models.IntegerField(default=0, verbose_name='Septiembre'),
        ),
    ]
