# Generated by Django 4.1.7 on 2023-06-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_anterior', models.FileField(upload_to='balance_anterior/', verbose_name='Balance Anterior')),
                ('archivo_actual', models.FileField(upload_to='balance_actual', verbose_name='Balance Actual')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
