# Generated by Django 4.1.7 on 2023-05-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancegeneral',
            name='archivo_actual',
            field=models.FileField(upload_to='balance_actual', verbose_name='Balance Actual'),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='archivo_anterior',
            field=models.FileField(upload_to='balance_anterior/', verbose_name='Balance Anterior'),
        ),
    ]
